CREATE DATABASE QUESTION2;
USE QUESTION2;
CREATE TABLE INCOME(
		S_NO INT primary KEY auto_increment,
        NAME VARCHAR(30),
        MONTHLY_INCOME INT(10),
        INNCOME_LEVEL VARCHAR(10));
INSERT INTO INCOME(NAME,MONTHLY_INCOME)
VALUES  ('SAM',4500),
		('RAMESH',4000),
        ('SURESH',5000),
        ('RAM',5200),
        ('DAVE',4900);
SELECT S_NO, NAME, MONTHLY_INCOME,
       CASE
           WHEN MONTHLY_INCOME <= 4000 THEN 'LOW INCOME'
           WHEN MONTHLY_INCOME <= 5000 AND MONTHLY_INCOME < 4000 THEN 'AVG INCOME'
           ELSE 'HIGH INCOME'
       END AS INCOME_LEVEL
FROM INCOME;
